- import_playbook: site.common.group-current-hosts.yml

- hosts: app:&current:!immutable
  gather_facts: no
  pre_tasks:
    - name: Wait for builder's SSH to become available
      wait_for_connection: ~

    - name: Gather facts for first time
      setup: ~

  roles:
    - role: cs.aws-node-facts
      delegate_to: localhost
      delegate_facts: no
      become: no
      when: aws_use
    - role: cs.aws-rds-facts
      delegate_to: localhost
      delegate_facts: no
      become: no
      when: aws_use
    - role: cs.switch-to-dnf
    - role: pinkeen.selinux-disable
      when: mageops_virtualization_full | default(true)
    - role: cs.swap
      when: mageops_swap_app_node_enable
    - role: cs.zram
      when: mageops_zram_app_node_enable and mageops_virtualization_full | default(true)
    - role: cs.earlyoom
      when: mageops_earlyoom_enable
    - role: cs.provisioning-migrations
    - role: cs.packages
    - role: cs.mageops-cli-profile
    - role: cs.mageops-cli-user
      mageops_cli_user_name: root
      mageops_cli_user_bashrc_fragments:
        - magento-root
    - role: cs.mageops-cli-user
      mageops_cli_user_name: "{{ magento_user }}"
      mageops_cli_user_group: "{{ magento_group }}"
      mageops_cli_user_uid: "{{ magento_uid }}"
      mageops_cli_user_gid: "{{ magento_gid }}"
      mageops_cli_user_umask: "{{ magento_umask }}"
      mageops_cli_user_bashrc_fragments:
        - magento
    - role: cs.mageops-authorize-keys
    - role: cs.magento-tools
    - role: cs.aws-cli
      when: aws_use
    - role: cs.cron
    - role: geerlingguy.ntp
    - role: cs.supervisor
    - role: cs.nginx
    - role: cs.nginx-url-blacklist
    - role: cs.nginx-magento
    - role: cs.nginx-https-termination
      when: mageops_app_node_https_termination_enable
    - role: cs.php-fpm
      tags: php
    - role: cs.varnish
      when: not varnish_standalone
    - role: cs.blackfire
      when: blackfire_install
    - role: cs.s3-fuse-s3fs
      when: aws_use and not s3fs_mount_use_goofys | default(false)
    - role: cs.s3-fuse-goofys
      when: aws_use and s3fs_mount_use_goofys | default(false)
    - role: pinkeen.postfix
    - role: pinkeen.postfix-relay
      when: mageops_app_email_smtp_relay_host | default(false, true) | bool
    - role: cs.magento-postfix
    - role: cs.aws-logs
      when: aws_use
    - role: cs.mageops-cli-profile

  tasks:
    - include_tasks: "{{ mageops_extra_tasks_app_node }}"
      when: mageops_extra_tasks_app_node is defined

  vars:
    mageops_node_role: app
