- import_playbook: site.common.group-current-hosts.yml

- hosts: "loadbalancer:&varnish"
  roles:
    - role: cs.nginx-url-blacklist
    - role: cs.nginx-https-termination
      when: https_termination
  vars:
    nginx_blacklist_urls: "{{ nginx_blacklist_urls_default + nginx_blacklist_urls_project | default([]) }}"

    