
- name: Ensure /var/lib/rpm-state exists (fix for https://access.redhat.com/solutions/3573891)
  file:
    path: /var/lib/rpm-state
    state: directory

- name: Get last package maintenance timestamp
  slurp:
    path: "{{ packages_maintenance_marker_path }}"
  register: packages_maintenance_last_timestamp
  changed_when: false
  failed_when: no

- name: Perform one-time package maintenance
  block:
    - name: Set localized yum mirrorlist for core repos
      ini_file:
        path: "/etc/yum.repos.d/{{ item.file }}"
        section: "{{ item.repo }}"
        option: mirrorlist
        value: "{{ item.url }}"
        backup: yes
        no_extra_spaces: yes
      loop: "{{ packages_mirrorlists }}"
      loop_control:
        label: "{{ item.repo }}"
      when: packages_mirrorlist_countrycode is defined and packages_mirrorlist_countrycode

    - name: Make sure banned packages are not present
      yum:
        name: "{{ packages_remove | default([]) }}"
        state: absent
      when: packages_remove is defined and packages_remove | length

    - name: Store information that package maintenance was done
      copy:
        content: "{{ ansible_date_time.epoch }}"
        dest: "{{ packages_maintenance_marker_path }}"
  when: >-
    packages_maintenance_last_timestamp.content is not defined or (
      (
        packages_maintenance_last_timestamp.content | int - ansible_date_time.epoch | int
      ) > packages_maintenance_interval | int
    )

- name: Make sure there are no open yum transactions
  shell: yum-complete-transaction -y --cleanup-only
  args:
    warn: no

- name: "Install packages"
  yum:
    name: "{{ packages_install }}"
    state: present
  register: packages_install_command
  retries: 5
  delay: 5
  until: not packages_install_command is failed

- name: "Ensure all packages are up to date"
  yum:
    name: '*'
    state: latest
    exclude: "{{ packages_full_update_exclude }}"
  when: packages_full_update

