- name: Update project DB configuration
  import_role:
    name: cs.mysql-configure-project

# Normally deploy does it, but we don't deploy to raccoon
- name: Add nginx to magento group
  user:
    name: "{{ nginx_user }}"
    groups: "{{ magento_group }}"
    append: yes

- name: Set up Magento installation (DEVELOPMENT)
  include_role:
    name: cs.magento-configure
    tasks_from: raccoon.yml
  when: not raccoon_project_production_mode

- name: Set up Magento installation (PRODUCTION)
  include_role:
    name: cs.magento-configure
  when: raccoon_project_production_mode